version: 2

sphinx:
  configuration: docs/conf.py

formats: all

build:
  os: ubuntu-24.04
  tools:
    python: '3.13'
  jobs:
    create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    install:
      - UV_PROJECT_ENVIRONMENT="$READTHEDOCS_VIRTUALENV_PATH" uv --project docs sync
