#!/bin/sh
# This is a Git pre-commit hook. Install it to `.git/hooks`.
#
# Run xgettext to write a new resources/l10n/template.pot, then add it to the
# commit if more than one line in it has changed, otherwise discard any changes
# to it.
set -e

xgettext \
  --keyword="translate:1,1t" \
  --keyword="translate:1,2,3t" \
  --add-location=full \
  --from-code=utf-8 \
  --package-name=LOOT \
  --package-version=0.16.0 \
  --copyright-holder="WrinklyNinja" \
  --msgid-bugs-address="https://github.com/loot/loot/issues" \
  -o resources/l10n/template.pot \
  src/gui/cef/query/*.h \
  src/gui/cef/query/types/*.h \
  src/gui/state/*.cpp \
  src/gui/state/game/*.cpp

sed -i 's|charset=CHARSET|charset=UTF-8|' resources/l10n/template.pot

# Run babel to generate a .po file for the JavaScript strings.
# Unfortunately this writes locations as absolute Windows-style paths, so turn
# them into relative unix-style paths afterwards.
yarn run babel --config-file ./scripts/xgettext.babel.json --no-babelrc ./src/gui/html --out-file=resources/l10n/discard.js --extensions ".ts,.tsx"
rm resources/l10n/discard.js
sed -i "/^#:/ s|\\\\|/|g" resources/l10n/js_template.po
sed -i "s|#: [A-Za-z]:${PWD:2}/|#: |" resources/l10n/js_template.po

# Now concat the two template files.
tail -n +5 resources/l10n/js_template.po >> resources/l10n/template.pot
rm resources/l10n/js_template.po

LINES_ADDED=$(git diff --numstat resources/l10n/template.pot | cut -f 1)
LINES_REMOVED=$(git diff --numstat resources/l10n/template.pot | cut -f 2)

if [ "$LINES_ADDED" = "$LINES_REMOVED" -a "$LINES_ADDED" = "1" ]; then
  git checkout -- resources/l10n/template.pot
else
  git add resources/l10n/template.pot
fi
